name: barterit
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  http: ^0.13.6
  image_cropper: ^4.0.1
  image_picker: ^0.8.8
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
